services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector-container
    environment:
      POSTGRES_USER: langchain
      POSTGRES_PASSWORD: langchain
      POSTGRES_DB: langchain
    ports:
      - "6024:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgvector_data:
# connection = "postgresql+psycopg://langchain:langchain@localhost:6024/langchain"
